server:
  port: 8081
  error:
    include-message: always
#Configuracion de spring
spring:
  #Configuracion de migracion
  flyway:
    enabled: true
    baselineVersion: 1
    locations:
      classpath: db/migration
    sqlMigrationSuffixes: .sql
    baselineOnMigrate: true
    sqlMigrationPrefix: V
    schemas: public

  datasource:
    url: jdbc:postgresql://ruby.db.elephantsql.com/tinzxbta?socketTimeout=3
    username: tinzxbta
    password: B5e4R_RV6sP9mtUtg8mBx-Kf6IJysWOI
    driverClassName: org.postgresql.Driver